setwd("~/R/csv/gerber")
gerber= read.csv("gerber.csv")
str(gerber)
table(gerber$voting)
table(gerber$voting)/nrow(gerber)
mod= lm(voting ~ hawthorne+civicduty+neighbours+self, data=gerber)
mod= lm(voting ~ hawthorne+civicduty+neighbors+self, data=gerber)
summary(mod)
table(gerber$voting, gerber$civicduty)
table(gerber$voting, gerber$civicduty, gerber$self)
summary(gerber)
table(gerber$voting, gerber$civicduty)
table(gerber$voting, gerber$self)
table(gerber$voting, gerber$hawthorne)
table(gerber$voting, gerber$neighbors)
tapply(gerber$voting, gerber$civicduty, mean)
tapply(gerber$voting, gerber$neighbors, mean)
logmod= glm(voting ~ hawthorne+civicduty+neighbors+self, data=gerber, family="bionomial")
logmod= glm(voting ~ hawthorne+civicduty+neighbors+self, data=gerber, family="binomial")
summary(logmod)
prdict= predict(logmod)
prdict= predict(logmod, type="response")
table(gerber$voting, prdict>0.3)
(134513+51966)/(134513+100875+56730+51966)
table(gerber$voting, prdict>0.5)
table(gerber$voting, prdict>0.5)
table(gerber$voting, prdict>0.4)
table(gerber$voting, prdict>0.3)
table(gerber$voting, prdict>0.2)
table(gerber$voting, prdict>0.5)
235388/(235388+108696)
setwd("~/R/csv/gerber")
gerber= read.csv("gerber.csv")
str(gerber)
attach(gerber)
detach(census)
attach(gerber)
tapply(gerber$voting, gerber$civicduty,mean)
table(gerber$voting, gerber$civicduty)
96675/(209191+96675)
names(gerber)
mini= glm(voting~ hawthorne+civicduty+nei+self, data=gerber, family = "binomial")
mini= glm(voting~ hawthorne+civicduty+neighbors+self, data=gerber, family = "binomial")
summary(mini)
pred= predict(mini)
table(gerber$voting,pred>0.3)
head(pred)
pred= predict(mini, type="response")
table(gerber$voting,pred>0.3)
(134513+51966)/nrow(gerber)
head(pred)
1+exp(-0.7789898)
1/1.458869
table(gerber$voting,pred>0.5)
table(gerber$voting,pred>0.3)
table(gerber$voting,pred>0.5)
235388/nrow(gerber)
table(gerber$voting)
library(ROCR)
predrocr= prediction(pred, gerber$voting)
auc= as.numeric(performance(predrocr,"auc")@y.values)
auc
regcart= rpart(voting~hawthorne+self+civicduty+neighbors, data= train)
regcart= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber)
prp(regcart)
prp(cart)
regcart1= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber, cp=0.0)
prp(regcart1)
regcart1= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber, cp=0.002)
prp(regcart)
prp(regcart1)
regcart1= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber, cp=0.0)
regcart2= rpart(voting~hawthorne+self+civicduty+neighbors+sex, data= gerber, cp=0.0)
prp(regcart2)
names(gerber)
savehistory("~/R/csv/gerber/ger.R")
regtree= rpart(voting~control, data=gerber, cp=0.0)
prp(regtree)
regtreesex= rpart(voting~control+sex, data=gerber, cp=0.0)
prp(regtreesex)
library(ROCR)
library(rpart)
library(rpart.plot)
gerber= read.csv("gerber.csv")
str(gerber)
attach(gerber)
detach(census)
attach(gerber)
tapply(gerber$voting, gerber$civicduty,mean)
table(gerber$voting, gerber$civicduty)
96675/(209191+96675)
names(gerber)
mini= glm(voting~ hawthorne+civicduty+nei+self, data=gerber, family = "binomial")
mini= glm(voting~ hawthorne+civicduty+neighbors+self, data=gerber, family = "binomial")
summary(mini)
pred= predict(mini)
table(gerber$voting,pred>0.3)
head(pred)
pred= predict(mini, type="response")
table(gerber$voting,pred>0.3)
(134513+51966)/nrow(gerber)
head(pred)
1+exp(-0.7789898)
1/1.458869
table(gerber$voting,pred>0.5)
table(gerber$voting,pred>0.3)
table(gerber$voting,pred>0.5)
235388/nrow(gerber)
table(gerber$voting)
library(ROCR)
predrocr= prediction(pred, gerber$voting)
auc= as.numeric(performance(predrocr,"auc")@y.values)
auc
regcart= rpart(voting~hawthorne+self+civicduty+neighbors, data= train)
regcart= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber)
prp(regcart)
prp(cart)
regcart1= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber, cp=0.0)
prp(regcart1)
regcart1= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber, cp=0.002)
prp(regcart)
prp(regcart1)
regcart1= rpart(voting~hawthorne+self+civicduty+neighbors, data= gerber, cp=0.0)
regcart2= rpart(voting~hawthorne+self+civicduty+neighbors+sex, data= gerber, cp=0.0)
prp(regcart2)
names(gerber)
savehistory("~/R/csv/gerber/ger.R")
